FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npx react-scripts --version || npm install react-scripts@5.0.1
COPY . .
EXPOSE 3000
CMD ["npx", "react-scripts", "start"]